codingdojo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'',include('codingground.urls', namespace="codingground")),
]

codingground/urls.py
from django.conf.urls import url
from .import views

app_name = "codingground"

urlpatterns = [
	
	url(r'^$', views.home_page, name='index'),
	url(r'^about/$', views.about_page, name='about'),
	url(r'^form/$', views.form_page, name='form'),
	#url(r'^syntaxdb/$', views.syntaxdb_page, name='syntaxdb'),

	#iFrame Urls Here:-

	#url(r'^syntaxdb/syntaxdb.com$', views.syntaxdb_iFrame, name='syntaxdb'),

	#Form Processing Urls Here:-

	url(r'^getdata/$', views.get_data, name='get_data'),

	url(r'^cleardata/$', views.clear_data, name='clear_data')
]

codingground/models.py
from __future__ import unicode_literals

from django.db import models

from django import forms

# Create your models here.

codingground/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse
from django.template import loader
from django.views.decorators.csrf import csrf_exempt

from django.views.generic import TemplateView

# Code Compilation Modules ##########################

import sys
import commands
import os
import subprocess
from subprocess import Popen, PIPE, STDOUT

######################################################

# Create your views here.

def home_page(request):
    return render(request, 'codingground/index.html', {})

def about_page(request):
    return render(request, 'codingground/about.html', {})

def form_page(request):
    return render(request, 'codingground/form.html', {})

#Form Processing View are Here:-

#disabling csrf (cross site request forgery)
@csrf_exempt

def get_data(request):
    
    #if post request came 
    if request.method == 'POST':
    
        #getting values from post
        extension = request.POST.get('extension')
        code = request.POST.get('code')
        user_input = request.POST.get('user_input')

        print "########################"
        print "#                      #"
        print "     Extension: %s      " % extension
        print "#                      #" 
        print "     Code: %s           " % code
        print "#                      #"
        print "     User Input: %s     " % user_input
        print "########################"

        if(extension == 'c'):

            fo = open('codingground/source_code/C/c_file.c','w+')
            fo.write(code);
            fo.close()

            s, v = commands.getstatusoutput('/usr/bin/gcc -o codingground/source_code/C/a.out codingground/source_code/C/c_file.c')
            
            if(s == 0):
                print "\nCode Compiled Successfully"
                commands.getoutput('chmod +x codingground/source_code/C/a.out')
                output = commands.getoutput('codingground/source_code/C/./a.out')
                print output
                return render(request, 'codingground/index.html', { 'extension': extension, 'code': code, 'output': output })

            else:
                print "\nCompilation Errors"
                print v
                output = v
                return render(request, 'codingground/index.html', { 'extension': extension, 'code': code, 'output': output })

        ############################################################

        if(extension == 'cpp'):

            fo = open('codingground/source_code/C++/cpp_file.cpp','w+')
            fo.write(code)
            fo.close()

            s, v = commands.getstatusoutput('/usr/bin/g++ -o codingground/source_code/C++/a.out codingground/source_code/C++/cpp_file.cpp')

            if(s == 0):
                print "\nCompiled Successfully"
                commands.getstatusoutput('chmod +x codingground/source_code/C++/a.out')
                output = commands.getoutput('codingground/source_code/C++/./a.out')
                print output
                return render(request, 'codingground/index.html', { 'extension': extension, 'code': code, 'output': output })

            else:
                print "\nCompilation Errors"
                print v
                output = v
                return render(request, 'codingground/index.html', { 'extension': extension, 'code': code, 'output': output })

        ######################################################################

        if(extension == 'java'):

            fo = open('codingground/source_code/Java/%s.java' % user_input,'w+')
            fo.write(code)
            fo.close()

            s, v = commands.getstatusoutput('/user/bin/javac codingground/source_code/Java/%s.java' % user_input)

            if(s == 0):

                commands.getstatusoutput('chmod +x codingground/source_code/Java/%s.java' % user_input)
                w = commands.getstatusoutput('/user/bin/java codingground/source_code/Java/%s.class' % user_input)

            return redirect('/')

        ##########################################################################

        if(extension == 'php'):

            fo = open('codingground/source_code/Php/php_file.php','w+')
            fo.write(code)
            fo.close()

            s, v = commands.getstatusoutput('/usr/bin/php codingground/source_code/Php/php_file.php')

            if(s == 0):
                print "\nCompiled Successfully"
                print v
                output = v
                return render(request, 'codingground/index.html', { 'extension': extension, 'code': code, 'output': output })

            else:
                print "\nCompilation Errors"
                print v
                output = v
                return render(request, 'codingground/index.html', { 'extension': extension, 'code': code, 'output': output })

        ##########################################################################

        if(extension == 'py'):

            fo = open('codingground/source_code/Python/python_file.py','w+')
            fo.write(code)
            fo.close()
            """s, v = commands.getstatusoutput('/usr/bin/python /home/tan/Desktop/codingdojo/codingground/source_code/Python/python_file.py')
            if(s == 0):
                print "\nCompiled Successfully"
                print v
                output = v
                return render(request, 'codingground/index.html', { 'extension': extension, 'code': code, 'output': output })
            else:
                print "Compilation Errors"
                print v
                output = v
                return render(request, 'codingground/index.html', { 'extension': extension, 'code': code, 'output': output })
            #return redirect('/')"""
            # First check compilation errors:-
            """
            s, v = commands.getstatusoutput('/usr/bin/python /home/tan/Desktop/codingdojo/codingground/source_code/Python/python_file.py')
            if(s == 0): # Compilation is a Success
                p = Popen(['/usr/bin/python','/home/tan/Desktop/codingdojo/codingground/source_code/Python/python_file.py'], stdout=PIPE, stdin=PIPE, stderr=STDOUT)
                stdout,stderr = p.communicate(input=user_input)
                output = stdout
                print p
                return render(request, 'codingground/index.html', { 'extension': extension, 'code': code, 'output': output })
            else: # Error in Compilation
                print "Compilation Errors"
                print v
                output = v
                return render(request, 'codingground/index.html', { 'extension': extension, 'code': code, 'output': output })
                """

            if(user_input):

                p = Popen(['/usr/bin/python','codingground/source_code/Python/python_file.py'], stdout=PIPE, stdin=PIPE, stderr=STDOUT)
                stdout,stderr = p.communicate(input=user_input)
                output = stdout
                print output
                return render(request, 'codingground/index.html', { 'extension': extension, 'code': code, 'output': output })


            else:
            
                s, v = commands.getstatusoutput('/usr/bin/python codingground/source_code/Python/python_file.py')
                
                if(s == 0):

                    print "\nCompiled Successfully"
                    print v
                    output = v
                    return render(request, 'codingground/index.html', { 'extension': extension, 'code': code, 'output': output })
            
                else:

                    print "Compilation Errors"
                    print v
                    output = v
                    return render(request, 'codingground/index.html', { 'extension': extension, 'code': code, 'output': output })

    else:
        return render(request, 'codingground/index.html', {})

@csrf_exempt

def clear_data(request):

    return redirect('/')

codingground/templates/codingground/about.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>
	<title>About</title>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">

	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	
	<script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<link href="//fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"> 
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>

<body class="about">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">&lt;Codenza/&gt;</a>
    </div>
    
    <div class="collapse navbar-collapse navbar-right" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'codingground:index' %}">Home</a></li>
        <li><a href="https://syntaxdb.com" target="_blank">Syntax</a></li>
        <li><a href="http://stackoverflow.com/search?q" target="_blank">Stack Overflow</a></li>
        <li><a href="#">About</a></li>
      </ul>
    </div>
  
  </div>
</nav>

<div class="jumbotron">
  <h1>&lt;Codenza/&gt; codingDojo</h1>
  <h5>Version - 1.0 beta</h5>      
  <p>Code in C, C++, Java, Php, Python.</p>
  <p>Made with Bootstrap, Sublime Text, Ubuntu fonts, Python-django Framework.</p>
  <div class="container">
  	<p class="note">Disclaimer: Online Compilers do not ask for user input explictly.</p>
  	<p class="note">Note: Standard Programming Libraries supported.</p>
  </div>
</div>

<div class="container">
	
	<div class="row">
		
		<div class="col-sm-5"><!--
			<h4>Download Tools:-</h4> -->
			<div class="table-responsive">
				<table class="table">
					<thead>
						<tr><h4>Download Tools:-</h4></tr>
					</thead>
					<tbody>
						<tr>
							<td><h5><a target="_blank" href="https://www.sublimetext.com/3">Sublime Text</a></h5></td>
						</tr>
						<tr>
							<td><h5><a target="_blank" href="https://github.com/atom/atom/releases">Atom</a></h5></td>
						</tr>
						<tr>
							<td><h5><a target="_blank" href="https://code.visualstudio.com/download">Visual Studio Code</a></h5></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>

		<div class="col-sm-2"></div>

		<div class="col-sm-5">
			<div class="table-responsive">
				<table class="table">
					<thead>
						<tr><h4>Made with Love by:-</h4></tr>
					</thead>
					<tbody>
						<tr>
							<td><h5><a href="#">Tanmoy karmokar</a></h5></td>
						</tr>
						<tr>
							<td><h5><a href="#">Suraj Pasi</a></h5></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>

	</div>

		<div class="row">
		
		<div class="col-sm-5"><!--
			<h4>Download Tools:-</h4> -->
			<div class="table-responsive">
				<table class="table">
					<thead>
						<tr><h4>Download our app from the Playstore:-</h4></tr>
					</thead>
					<tbody>
						<tr>
							<td><h5><a target="_blank" href="https://play.google.com/store/apps/details?id=com.codenza.dp.programs&hl=en">Codenza</a></h5></td>
						</tr>
					</tbody>
				</table>
			</div>

			<div class="table-responsive">
				<table class="table">
					<thead>
						<tr>
							<h4>Codenza codingDojo Repo:-</h4>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<h5><a href="#">Github</a></h5>
							</td>
						</tr>
					</tbody>
				</table>
				
			</div>

		</div>

		<div class="col-sm-2"></div>

		<div class="col-sm-5">
			<div class="table-responsive">
				<table class="table">
					<thead>
						<tr><h4>Our App Developers + Core Team:-</h4></tr>
					</thead>
					<tbody>
						<tr>
							<td><h5><a href="#">Pratik Paranjape</a></h5></td>
							<td><h5><a href="#">Ninad Yadav</a></h5></td>
						</tr>
						<tr>
							<td><h5><a href="#">Divyendra Patil</a></h5></td>
							<td><h5><a href="#">Tanmoy Karmokar</a></h5></td>
						</tr>
						<tr>
							<td><h5><a href="#">Prasad Rajarshi</a></h5></td>
							<td><h5><a href="#"></a></h5></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>

	</div>

</div>

<div id="footer" class="bottom">
	<p class="muted-credit">Coding ground by Codenza. All rights reserved.</p>
</div>


</body>

</html>

codingground/templates/codingground/form.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>
	
	<title>Codenza</title>
	
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">

	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	
	<script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<link href="//fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"> 
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>

<body>

<div class="col-sm-4"></div>

<div class="col-sm-4">

	<h3>Programming Language: <h4>{{ extension }}</h4></h3>
	<br><br><br>

	<h3>Code Input by User:</h3>

	<h4>
		{{ code }}
	</h4>

	<br><br><br>

	<h3>Code Output:</h3>

	<h4> {{ output }}</h4>

</div>

<div class="col-sm-4"></div>

</body>

</html>

codingground/templates/codingground/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>
	<title>&lt;Codenza/&gt;</title>
	
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">

	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	
	<script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<link href="//fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"> 
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  
  <!--
  <script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>

  <script src="{% static 'js/script.js' %}"></script> -->

</head>

<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">&lt;Codenza/&gt;</a>
    </div>
    
    <div class="collapse navbar-collapse navbar-right" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="#">
            Home
            </a>
        </li>
        
        <li><a href="https://syntaxdb.com" target="_blank">
            Syntax
            </a>
        </li>
        
        <li><a href="http://stackoverflow.com/search?q" target="_blank">
            Stack Overflow
            </a>
        </li>
        
        <li><a href="{% url 'codingground:about' %}">
            About
            </a>
        </li>
      </ul>
    </div>
  
  </div>
</nav>

<div class="container">

	<h3>Code in C, C++, Java, Php, Python</h3>

  <div class="row">
    
    <div class="col-sm-6">
      <h4 class="win1">Code Window</h4>

      <form action="/getdata/" method="POST">

        <div class="form-group">
            <p class="source">Enter Source Type: c / cpp / java / php / py. </p>
            <input type="text" class="form-control" id="source_type" name="extension" value="{{ extension }}" required>
            <input type="text" class="form-control" id="u_input" name="user_input" placeholder="Enter user variables here / Class name for Java">
        </div>
        
        <div class="form-group">
            <textarea class="form-control" rows="20" name="code" id="comment" required>{{ code }}</textarea>
        </div>
        
        <button type="submit" class="btn btn-primary">Run Code</button>
      
      </form>
    
    </div>
    
    <div class="col-sm-6">
      <h4 class="win1">See Output</h4>

      <form action="/cleardata/" method="POST" >

        <div class="form-group">
            <p class="source">Syntax / Compilation Errors, shown below.</p>
            
            <p>
              <!-- <label for="u_input">User Input:</label>
              <input type="text" class="form-control" id="u_input" name="user_input" value="Enter user variables here / Class name for Java"> -->
            </p>
        </div>
        
        <div class="form-group">
            <textarea class="form-control" rows="24" name="output" id="comment">{{ output }}</textarea>
        </div>
        
        <button type="submit" class="btn btn-primary">Clear Output</button>
      
      </form>

    </div>
  
  </div>
</div>

<br>

    <div id="footer" class="bottom">
        <p class="muted-credit">Coding ground by Codenza. All rights reserved.</p>
    </div>

</body>

</html>

codingground/templates/codingground/syntaxdb.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>
	<title>Check Syntax</title>
	
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">

	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	
	<script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<link href="//fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"> 
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body class="about">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">&lt;Codenza/&gt;</a>
    </div>
    
    <div class="collapse navbar-collapse navbar-right" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="#">Home</a></li>
        <li><a href="{% url 'codingground:syntaxdb' %}" target="_blank">Syntax</a></li>
        <li><a href="#">Stack Overflow</a></li>
        <li><a href="{% url 'codingground:about' %}">About</a></li>
      </ul>
    </div>
  
  </div>
</nav>

<div class="row">

  <br>
  
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <h4 class="note">Got any syntax doubts...??? We got that covered up too...!!!</h4>
  </div>
  <div class="col-sm-3"></div>

</div>

<!-- Responsive Iframe -->

<div class="embed-responsive embed-responsive-16by9">
  
  <iframe class="embed-responsive-item" src="/syntaxdb.com"></iframe>

</div> <!--

<iframe src="google.com"></iframe> -->

</body>

</html>